# cluster.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: raksha-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 3000
        protocol: TCP

  - role: worker
  - role: worker

